apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flask-docker
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: flask-docker
              servicePort: http
