apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: flask-docker
images:
- name: flask-docker
  newName: /flask-docker
  newTag: 64f7907b9dac84a575a3e43e6f44340e577efc81
