apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-docker
  name: flask-docker
spec:
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app: flask-docker
  type: ClusterIP
