apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-docker
spec:
  tls:
  - hosts:
    - www.bergerud.dev
    secretName: cloudflare-tls
  rules:
  - host: www.bergerud.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-docker
            port:
              name: http
