apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- flask-namespace.yaml
namespace: flask-docker
images:
- name: flask-docker
  newName: obergeru/flask-docker
  newTag: 1e825debcc346e369767472a15f1a0a1e4a51489
