name: Docker Image CI and security scanning
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag obergeru/flask-docker:${{ github.sha }}


            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                      image-ref: 'obergeru/flask-docker:${{ github.sha }}'
                      format: 'template'
                      template: '@/contrib/sarif.tpl'
                      output: 'trivy-results.sarif'
                      severity: 'CRITICAL,HIGH'

            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v1
              with:
                      sarif_file: 'trivy-results.sarif'

            - name: Build and push dockerimage
              uses: docker/build-push-action@v1.1.0
              with:
                      username: ${{ secrets.DOCKERHUB_USERNAME }}
                      password: ${{ secrets.DOCKERHUB_TOKEN }}
                      repository: ${{ secrets.DOCKERHUB_USERNAME }}/flask-docker
                      tags: ${{ github.sha }}, latest
